### ISSUE TITLE
Issue when sending message and IDs made with only strings.

### ISSUE THREAD

**Issue by CommanderByte** [illuminated-g/lv-levis-tcp#1]
Hello,

I think I have found a bug in the Tiny TCP Library hosted on VIPM for LV 2021 64 bit, concerning data transmission in the malleable "Write Message" VIM when used with Strings for both the ID and Message (At least in LabView 2021 64-bit).

I have made the following VI using your library and have noted the following results on the front panel, as you can see the message and ID are garbled upon reception back to the client:

![image](https://user-images.githubusercontent.com/1491782/216793943-590cea37-639c-47b4-9891-91ef69f671df.png)

Below is the block diagram of the above front panel:

![image](https://user-images.githubusercontent.com/1491782/216794048-d134f48b-404e-4879-905f-9750720f1869.png)

After investigation, I have traced the error to the "Flatten to String" function present inside the "Write Message" VIM: 

![image](https://user-images.githubusercontent.com/1491782/216794221-ed28e343-4bb3-45ef-90e2-f3a8d475ec25.png)

It seems that when creating the message, that the length of the combined message/ID string is automatically append to the outgoing data to be written over TCP (see black circle). However, I have noticed that the flatten to string functions also do this by default, and seems to be the source of the garbling as it is writing string length data in the ID and message:

![image](https://user-images.githubusercontent.com/1491782/216794285-a262d1ee-3763-46e6-a36f-2ceb5e7e9be5.png)

Setting this value to False for both flattens shown with the arrows through the use of a constant seems to solve the issue, at least with strings only:

![image](https://user-images.githubusercontent.com/1491782/216794548-204b9c7d-eb0a-4dab-bdc3-d3bbf8a92c83.png)

I'm not sure why this issue is occuring, as it seems that the read/write VIMs pack and unpack data from strings taking into account this on both ends...

Kind regards,

**Comment by negentropicdev** [comment]
@mrlinuxguy There's still got to be a mismatch in the write and read formatting, lemme take a look. The intent is to leave all the length prepending on but I might still have some special handling for string data on the read formatting that I thought I had taken out.

**Comment by negentropicdev** [comment]
Alright it has to do with the way reads are intended to support returning the raw data to be able to choose how to unflatten based on the message ID. I'm changing the type input on the read vim to be able to differentiate between an unwired type input which should return the raw data and wiring a string to it which will strip off the prepended length.

**Comment by negentropicdev** [comment]
Package has been updated on VIPM to 1.0.0.5 and should fix handling for string data types. Once you restart VIPM or refresh the package list you'll be able to update. This update does require wiring a string constant or other string wire type into the Data Type input of the Read Message.vim to properly handle plain strings as message data now. Let me know if you have any further issues.

**Comment by CommanderByte** [comment]
Have just updated the package, and can confirm it now works correctly with the wiring of a string constant for Read Message.vim! Thank you for the quick fix!

**Comment by negentropicdev** [comment]
Thanks for making the effort of publishing it worth it (people are using it, yay!) and contributing to its improvement.
