### ISSUE TITLE
suggestion : add wait for connection vi to the palette

### ISSUE THREAD

**Issue by AntoineChalons** [illuminated-g/lv-levis-tcp#2]
add the 'wait for connection.vi' to the palette

![image](https://user-images.githubusercontent.com/1894167/231972051-a01906ce-61a9-4d68-96a9-16217e2cd23d.png)

**Comment by negentropicdev** [comment]
Done, released as new package version 1.0.1.6

Thanks for catching my miss!

**Comment by AntoineChalons** [comment]
that was fast, thanks!
