### ISSUE TITLE
misleading timeout units (ms instead of s) in Wait for conneciton.vi

### ISSUE THREAD

**Issue by AntoineChalons** [illuminated-g/lv-levis-tcp#3]
![image](https://user-images.githubusercontent.com/1894167/231991516-03450c13-bd8b-40bc-a4d6-c6270409248b.png)

call it what you want, misleading timeout unit or simply "bug"

**Comment by negentropicdev** [comment]
Bug :-D

**Comment by negentropicdev** [comment]
Fixed to be actually mS in 1.0.2.7
